name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
     - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: |
          yarn install  

      - name: Install Cypress
        run: |
          npm install cypress --save-dev 

      - name: Run Cypress tests
        run: |
          npx cypress run  
        env:
          CI: true 

